### ISSUE TITLE
getticktime tps seems to actually be mspt

### ISSUE THREAD

**Issue by potjesoep** [ElectroluxV2/git-backup-fabric-mod#2]
hi i noticed the getticktime in this seems to actually get the time it took for a tick to complete rather than the tps, i noticed this because it was skipping backups because of low tps even though the tps was 20, but the mspt (or time per tick in ms) was about 5

https://github.com/ElectroluxV2/git-backup-fabric-mod/blob/b1b335107ebaa2dc6ce7de58a9fd5b3c3ad7874f/src/main/java/com/github/electroluxv2/utils/BackupScriptParameters.java#L16

i fixed it really simply by just changing this line from < 10 to > 50 (it would skip backups if tps is under 20, since tps 20 is the same as 50, mspt

https://github.com/ElectroluxV2/git-backup-fabric-mod/blob/b1b335107ebaa2dc6ce7de58a9fd5b3c3ad7874f/src/main/resources/backup-scripts/on-save.sh#L14

to get the intended functionality (skipping under 10tps, you would have to check if it's not over 100mspt)

sorry i didn't create a pull request, i don't have access to git on my windows machine i hope this helps

**Comment by ElectroluxV2** [comment]
Thanks, will fix this soon.

**Comment by ElectroluxV2** [comment]
Resolved in 1.2.0
